In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import files
uploaded = files.upload()
#2.veri onisleme
#2.1.veri yukleme
veriler = pd.read_csv('Churn_Modelling.csv')

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [ ]:
X = veriler.iloc[:,3:13].values
Y = veriler.iloc[:,13:].values

In [ ]:
from sklearn import preprocessing

In [ ]:
le = preprocessing.LabelEncoder()
X[:,1] = le.fit_transform(X[:,1])
print(X)

[[619 0 'Female' ... 1 1 101348.88]
 [608 2 'Female' ... 0 1 112542.58]
 [502 0 'Female' ... 1 0 113931.57]
 ...
 [709 0 'Female' ... 0 1 42085.58]
 [772 1 'Male' ... 1 0 92888.52]
 [792 0 'Female' ... 1 0 38190.78]]


In [ ]:
le2 = preprocessing.LabelEncoder()
X[:,2] = le2.fit_transform(X[:,2])
print(X)

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
ohe = ColumnTransformer(["ohe",OneHotEncoder(dtype=float),[1]],remainder="passthrough")

In [ ]:
for i in range(10):
    print(X[i])

[619 0 0 42 2 0.0 1 1 1 101348.88]
[608 2 0 41 1 83807.86 1 0 1 112542.58]
[502 0 0 42 8 159660.8 3 1 0 113931.57]
[699 0 0 39 1 0.0 2 0 0 93826.63]
[850 2 0 43 2 125510.82 1 1 1 79084.1]
[645 2 1 44 8 113755.78 2 1 0 149756.71]
[822 0 1 50 7 0.0 2 1 1 10062.8]
[376 1 0 29 4 115046.74 4 1 0 119346.88]
[501 0 1 44 4 142051.07 2 0 1 74940.5]
[684 0 1 27 2 134603.88 1 1 1 71725.73]


In [ ]:
ohe = ColumnTransformer([("ohe",OneHotEncoder(dtype=float),[1])],remainder="passthrough")
X = ohe.fit_transform(X)
X = X[:,1:]

In [ ]:
print(X[0])

[0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


In [ ]:
# verilerin eğitim ve test için bölünmesi
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.33,random_state=0)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

In [ ]:
# yapay sinir ağları

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
classifier = Sequential()
classifier.add(Dense(6,kernel_initializer="uniform",activation="relu", input_dim=11))
classifier.add(Dense(12,kernel_initializer="uniform",activation="relu"))
classifier.add(Dense(18,kernel_initializer="uniform",activation="relu"))
classifier.add(Dense(12,kernel_initializer="uniform",activation="relu"))
classifier.add(Dense(6,kernel_initializer="uniform",activation="relu"))
classifier.add(Dense(1,activation="sigmoid"))
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [ ]:
classifier.fit(X_train,y_train,epochs=30)

Epoch 1/30
210/210 [==============================] - 1s 4ms/step - loss: 0.5390 - accuracy: 0.7970
Epoch 2/30
210/210 [==============================] - 1s 4ms/step - loss: 0.4388 - accuracy: 0.7979
Epoch 3/30
210/210 [==============================] - 1s 4ms/step - loss: 0.4267 - accuracy: 0.7979
Epoch 4/30
210/210 [==============================] - 1s 4ms/step - loss: 0.4223 - accuracy: 0.7979
Epoch 5/30
210/210 [==============================] - 1s 4ms/step - loss: 0.4180 - accuracy: 0.8106
Epoch 6/30
210/210 [==============================] - 1s 4ms/step - loss: 0.4167 - accuracy: 0.8218
Epoch 7/30
210/210 [==============================] - 1s 4ms/step - loss: 0.4157 - accuracy: 0.8248
Epoch 8/30
210/210 [==============================] - 1s 4ms/step - loss: 0.4146 - accuracy: 0.8257
Epoch 9/30
210/210 [==============================] - 1s 4ms/step - loss: 0.4136 - accuracy: 0.8273
Epoch 10/30
210/210 [==============================] - 1s 4ms/step - loss: 0.4125 - accuracy: 0.8297

In [ ]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[2551   66]
 [ 472  211]]
